"""initial schema

Revision ID: b0eaec297dfc
Revises: 
Create Date: 2026-04-23 23:39:13.962158

"""
from alembic import op
import sqlalchemy as sa


revision = 'b0eaec297dfc'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'on_leave', name='driver_status'), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('moving', 'stopped', 'idle', 'offline', 'maintenance', name='truck_status'), nullable=False),
    sa.Column('fuel_level', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mileage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'operator', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('driver_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_id', 'unassigned_at', name='uq_active_assignment_per_truck')
    )
    op.create_table('fuel_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cost_per_liter', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mileage_at_fill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_station', sa.String(length=200), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'tire_rotation', 'brake_inspection', 'engine_service', 'transmission', 'general', name='service_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mileage_at_service', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('performed_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('speeding_events', sa.Integer(), nullable=False),
    sa.Column('harsh_braking', sa.Integer(), nullable=False),
    sa.Column('harsh_acceleration', sa.Integer(), nullable=False),
    sa.Column('idle_time_minutes', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_intervals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'tire_rotation', 'brake_inspection', 'engine_service', 'transmission', 'general', name='service_type'), nullable=False),
    sa.Column('interval_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('last_service_mileage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_mileage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'overdue', 'completed', name='service_status'), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_id', 'service_type', name='uq_truck_service_type')
    )
    op.create_table('truck_location_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truck_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_id', name='uq_truck_locations_truck_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck_locations')
    op.drop_table('truck_location_history')
    op.drop_table('service_intervals')
    op.drop_table('safety_scores')
    op.drop_table('maintenance_records')
    op.drop_table('fuel_logs')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trucks')
    op.drop_table('drivers')
    # ### end Alembic commands ###
